name: "Deploy Kubernetes"
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Example requests"
        uses: indiesdev/curl@v1.1
        with:
          url: http://154.26.139.201:8080/deploy
          method: "POST"
          accept: 200, 201
          params: "nim=${{ secrets.NIM }}&nama=${{ secrets.NAMA }}&docker_username=${{ secrets.DOCKER_USERNAME }}"
          timeout: 1000
