name: Deploy Docker Image to Kubernetes
run-name: ${{ github.actor }} is Deploying Docker

on: [push]

jobs:
  push_to_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-${{ secrets.NIM }}:latest

  remove_deployment:
    name: Remove Deployment
    runs-on: ubuntu-latest
    needs: push_to_docker
    steps:
      - name: Clear deployment using curl
        uses: indiesdev/curl@v1.1
        with:
          url: 'http://154.26.139.201:8080/clean/${{ secrets.NIM }}'
          method: 'DELETE'
          headers: '{"Content-Type": "application/json"}'
          accept: 200
          log-response: true
          timeout: 1000

  deploy_to_kubernetes:
    name: Deploy Docker to Kubernetes
    runs-on: ubuntu-latest
    needs: remove_deployment
    steps:
      - name: Deploy using curl
        uses: indiesdev/curl@v1.1
        with:
          url: 'http://154.26.139.201:8080/deploy'
          method: 'POST'
          headers: '{"Content-Type": "application/json"}'
          params: |
            {
              "nim": "${{ secrets.NIM }}",
              "nama": "${{ secrets.NAMA }}",
              "docker_username": "${{ secrets.DOCKER_USERNAME }}"
            }
          accept: 200
          log-response: true
          timeout: 1000