name: Kube Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Deploy to Kubernetes
      env:
        SERVER_URL: http://154.26.139.201:8080
        NIM: ${{ secrets.NIM }}
        NAMA: ${{ secrets.NAMA }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: |
        curl -X POST "$SERVER_URL/deploy?nim=$NIM&nama=$NAMA&docker_username=$DOCKER_USERNAME"

  clean:
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Clean deployment by NIM
      env:
        SERVER_URL: http://154.26.139.201:8080
        NIM: ${{ secrets.NIM }}
      run: |
        curl -X DELETE "$SERVER_URL/clean/$NIM"

  get-index:
    runs-on: ubuntu-latest
    needs: [deploy]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Get index
      env:
        SERVER_URL: http://154.26.139.201:8080
      run: |
        curl -X GET "$SERVER_URL/"
